##
##	中继服务器配置 (Forward Server Config)
##
## 中继服务器一般是安装双网卡的主机，一块网卡与终端连接，另一块与
## 媒体服务器连接，需要分别指定这两个网络接口的地址。还需要配置媒
## 体服务器地址以及控制报文接收端口。	
##
##

[Config]

;; 媒体服务器地址
Server_Addr = 127.0.0.1

;; 与媒体服务器连接的网络接口地址
Server_Side_Addr = 127.0.0.1

;; 与终端连接的网络接口地址
Term_Side_Addr = 127.0.0.1

;; 组播地址范围
Use_Multicast = 1
Multicast_TTL = 1
Min_GroupAddr = 225.101.1.1
Max_GroupAddr = 225.101.1.253

;; 日志文件回滚天数(即日志文件保留的天数)
Log_Rotate_Days=15
 
;; 配置的终端数目
Config_Term_Count = 0

;; 终端是否允许组播
;; 0－不允许，1－允许
[Term_1]
IP_Addr = 192.168.0.100
Use_Multicast = 0


