set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET i686-w64-mingw32)
set(CMAKE_CXX_COMPILER_TARGET i686-w64-mingw32)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_clang_mingw_flags "--target=i686-w64-mingw32")

if(DEFINED ENV{MINGW_SYSROOT})
  set(CMAKE_SYSROOT "$ENV{MINGW_SYSROOT}")
  string(APPEND _clang_mingw_flags " --sysroot=$ENV{MINGW_SYSROOT}")
elseif(EXISTS "/mingw32")
  set(CMAKE_SYSROOT "/mingw32")
  string(APPEND _clang_mingw_flags " --sysroot=/mingw32")
endif()

if(DEFINED ENV{MINGW_GCC_TOOLCHAIN})
  set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN "$ENV{MINGW_GCC_TOOLCHAIN}")
  set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN "$ENV{MINGW_GCC_TOOLCHAIN}")
  string(APPEND _clang_mingw_flags " --gcc-toolchain=$ENV{MINGW_GCC_TOOLCHAIN}")
elseif(EXISTS "/mingw32")
  set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN "/mingw32")
  set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN "/mingw32")
  string(APPEND _clang_mingw_flags " --gcc-toolchain=/mingw32")
endif()

set(CMAKE_C_FLAGS_INIT "${_clang_mingw_flags}")
set(CMAKE_CXX_FLAGS_INIT "${_clang_mingw_flags}")
