[FormPos]
TfmMain=2,0,0,1024,740

[Option]
ServerMode=0
Font=宋体,9,clWindowText,134,0
Language=Simplified Chinese
Company_Website=
BigIcon=0
SunkenBorder=1
ViewStyle=1
LockedBar=1
SplashMode=1
Max_Mp3_Bps=500
Bps_Use_Avg=0
Username=admin
Password=admin
Monitor=25
RecordSourceIndex=0
UsePlayStudio=1
;; 实时文件播放优先级，默认值400
sprfile=400
;; 实时采播优先级，默认值500
sprtime=500
LoadRecordMgrModule=0
MapMonitorPath=C:\Program Files\CT-MapMonitor\C_GIS.exe
EnableMapMointor=0
RefreshInterval=60000


