[C_SvcDog]
;; 监控间隔（单位：毫秒）
monitor_interval=5000

;; 是否强制拉起，默认为0
;; 0 : 当被监控的服务异常退出时，拉起
;; 1 : 当被监控的服务停止时，拉起
is_always_rise=0

;; 服务数目
service_num = 10

[service_1]
;; 服务名称
name=C_Media
;; 服务描述
desc=IP网络广播 2.0 媒体服务
;; 监控标志, 为1表示监控, 为0表示不监控。
monitor=1

[service_2]
name=C_Proxy
desc=IP网络广播 2.0 代理服务
monitor=1

[service_3]
name=C_Forwd
desc=IP网络广播 2.0 中继服务
monitor=1

[service_4]
name=C_RTime
desc=IP网络广播 2.0 采播服务
monitor=1

[service_5]
name=C_Task
desc=IP网络广播 2.0 任务服务
monitor=1

[service_6]
name=C_SMerger
desc=IP网络广播 2.0 对讲录音合成服务
monitor=1

[service_7]
name=sndrec
desc=IP网络广播 2.0 录音服务
monitor=1

[service_8]
name=SIPService
desc=IP网络广播 2.0 SIP服务
monitor=1

[service_9]
name=C_ChannelSvr
desc=IP网络广播 2.0 频道服务
monitor=1

[service_10]
name=C_RadioSvr
desc=IP网络广播 2.0 电台服务
monitor=1
