;; 所有终端默认的采样增益，取值范围[0-255]，默认值为0
;; 为0时：终端的采样增益倍数为终端默认倍数
;; 为非0时：终端的采样增益倍数为enc_gain/8
[Default]
enc_gain = 0



;; 配置指定终端的采样增益
;; id - 终端ID
;; enc_gain - 该终端的采样增益
;;[Term_1]
;;id = 5
;;enc_gain = 0

;;[Term_2]
;;id = 6
;;enc_gain = 0


;; 注意：添加或删除指定终端的采样增益配置时，
;;       需保证配置组名称中下划线后面的序号连续，且从Term_1开始
;;   如：[Term_1]
;;       [Term_2]
;;       [Term_3]

