[Server]
;;服务器IP地址
ip=127.0.0.1
;;服务器命令端口
cmdport=8000
;;服务器数据端口
dataport=15001
;;超时时间
timeout=10
;;WEB服务端口
webport=8080
;;坐席终端Id
CallTerm=7
;;坐席终端名称
CallTermName=

[Login]
;;登录用户名
user=admin
;;登录用户密码
pass=admin
;;保存用户名
SaveUserName=1
;;保存用户密码
SavePassword=1

[Door]
;;门端口
port=1
;;门开值
open=0
;;门关值
close=1

[UI]
name=IP广播客户端
;;0-标准版本 1-简化版本
version=1

[Option]
sprfile=400
sprtime=500

